{inputs, self, lib, ...}: {
  flake.nixosConfigurations.nixos-gaming = inputs.nixpkgs.lib.nixosSystem rec {
    system = "x86_64-linux";
    modules = [
      self.nixosModules.general
      self.nixosModules.hyprland
      self.nixosModules.nvidia
      self.nixosModules.matteob
      self.nixosModules.stdPkgs
      self.nixosModules.dolphin
      self.nixosModules.neovim
      self.nixosModules.games
      self.nixosModules.terminal
      self.nixosModules.docker
      self.nixosModules.gamingConfig
      self.nixosModules.gamingHardware
      inputs.nix-index-database.nixosModules.default
      { programs.nix-index-database.comma.enable = true; }
    ];

  };
  flake.nixosModules.gamingConfig = { config, lib, pkgs, ... }: {

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.kernelPackages = pkgs.linuxKernel.packages.linux_7_1; #nvidia bruh

  networking.hostName = "nixos-gaming"; # Define your hostname.

  time.timeZone = "Europe/Amsterdam";

  fileSystems."/mnt/D" = {
    device = "/dev/disk/by-uuid/e1dad93f-07c6-414c-ab7a-479defa2a672";
    fsType = "btrfs";
    options = [
      "defaults"
      "nofail"
      "compress=zstd"
      "autodefrag"
    ];
    depends = ["/"];
  };

  fileSystems."/mnt/Z" = {
    device = "/dev/disk/by-uuid/36475945-32c0-465f-8d37-d6c987a6729f";
    fsType = "btrfs";
    options = [
      "defaults"
      "nofail"
      "compress=zstd"
      "autodefrag"
    ];
    depends = ["/"];
  };

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "fr_BE.UTF-8";
    LC_IDENTIFICATION = "fr_BE.UTF-8";
    LC_MEASUREMENT = "fr_BE.UTF-8";
    LC_MONETARY = "fr_BE.UTF-8";
    LC_NAME = "fr_BE.UTF-8";
    LC_NUMERIC = "fr_BE.UTF-8";
    LC_PAPER = "fr_BE.UTF-8";
    LC_TELEPHONE = "fr_BE.UTF-8";
    LC_TIME = "fr_BE.UTF-8";
  };

  # Configure keymap in X11
  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };


  # Enable CUPS to print documents.
  # services.printing.enable = true;

  services.thermald.enable = true;

  services = {
    jellyfin = {
      enable = true;
      openFirewall = true;
    };
    sonarr = {
      enable = true;
      # user = "matteob";
      # dataDir = "/home/matteob/.config/NzbDrone";
    };
    prowlarr = {
      enable = true;
    };
    flaresolverr.enable = true;
    # nix-serve = {
    #   enable = true;
    #   secretKeyFile = "../../secrets/cache-priv-key.pem";
    #   openFirewall = true;
    # };
  };

  environment.systemPackages = with pkgs; [
    # suwayomi-server
    jellyfin
    jellyfin-web
    jellyfin-ffmpeg
    # jellyfin-desktop
    fladder
    # winboat
    # bitwarden-desktop
  ];

  # Enable the OpenSSH daemon.
  # services.openssh.enable = true;

  # Open ports in the firewall.
  networking.firewall.allowedTCPPorts = [
    8080
    5173

    9998
    9999

    # 4567 #suwayomi
  ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  networking.firewall.allowedUDPPorts = [22000 21027]; #syncthing
  # Or disable the firewall altogether.
  # networking.firewall.enable = false;

  # Copy the NixOS configuration file and link it from the resulting system
  # (/run/current-system/configuration.nix). This is useful in case you
  # accidentally delete configuration.nix.
  # system.copySystemConfiguration = true;

  system.stateVersion = "25.05"; # DO NOT TOUCH UNDER ANY CIRCUMSTANCES
};

  flake.nixosModules.gamingHardware =
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ffccc19e-43fa-4862-ac96-485618248325";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FE9B-229A";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/e1539881-129c-4890-bc53-8dd5fdf79cb2";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp37s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
};
}

